# TypeProf 0.21.8

# Classes
module Foobar
  VERSION: String

  class Calculator
    @x: Integer

    def initialize: (Integer x) -> void
    def plus_x: (Integer y) -> Integer
    def plus_rand: (Integer y) -> Integer
  end

  class EntryPoint
    def start: -> void
    def run: (Integer n) -> void
    def print_usage_and_exit: -> bot
    def print_version_and_exit: -> bot
  end
end
